# Comprehensive list of worldwide airports
# Organized by region for easy maintenance

AIRPORTS = [
    # ============ NIGERIA ============
    {"code": "LOS", "name": "Lagos", "fullName": "Murtala Muhammed International Airport", "country": "Nigeria"},
    {"code": "ABV", "name": "Abuja", "fullName": "Nnamdi Azikiwe International Airport", "country": "Nigeria"},
    {"code": "PHC", "name": "Port Harcourt", "fullName": "Port Harcourt International Airport", "country": "Nigeria"},
    {"code": "KAN", "name": "Kano", "fullName": "Mallam Aminu Kano International Airport", "country": "Nigeria"},
    {"code": "ENU", "name": "Enugu", "fullName": "Akanu Ibiam International Airport", "country": "Nigeria"},
    {"code": "BNI", "name": "Benin City", "fullName": "Benin Airport", "country": "Nigeria"},
    {"code": "CBQ", "name": "Calabar", "fullName": "Margaret Ekpo International Airport", "country": "Nigeria"},
    {"code": "QOW", "name": "Owerri", "fullName": "Sam Mbakwe International Cargo Airport", "country": "Nigeria"},
    {"code": "ILR", "name": "Ilorin", "fullName": "Ilorin International Airport", "country": "Nigeria"},
    {"code": "JOS", "name": "Jos", "fullName": "Yakubu Gowon Airport", "country": "Nigeria"},
    {"code": "MIU", "name": "Maiduguri", "fullName": "Maiduguri International Airport", "country": "Nigeria"},
    {"code": "SKO", "name": "Sokoto", "fullName": "Sadiq Abubakar III International Airport", "country": "Nigeria"},
    {"code": "YOL", "name": "Yola", "fullName": "Yola Airport", "country": "Nigeria"},
    {"code": "AKR", "name": "Akure", "fullName": "Akure Airport", "country": "Nigeria"},
    {"code": "ABB", "name": "Asaba", "fullName": "Asaba International Airport", "country": "Nigeria"},
    {"code": "MDI", "name": "Makurdi", "fullName": "Makurdi Airport", "country": "Nigeria"},
    {"code": "QUO", "name": "Uyo", "fullName": "Ibom International Airport", "country": "Nigeria"},
    {"code": "KAD", "name": "Kaduna", "fullName": "Kaduna Airport", "country": "Nigeria"},
    {"code": "MXJ", "name": "Minna", "fullName": "Minna Airport", "country": "Nigeria"},
    {"code": "ZAR", "name": "Zaria", "fullName": "Zaria Airport", "country": "Nigeria"},

    # ============ WEST AFRICA ============
    {"code": "ACC", "name": "Accra", "fullName": "Kotoka International Airport", "country": "Ghana"},
    {"code": "KMS", "name": "Kumasi", "fullName": "Kumasi Airport", "country": "Ghana"},
    {"code": "TML", "name": "Tamale", "fullName": "Tamale Airport", "country": "Ghana"},
    {"code": "DSS", "name": "Dakar", "fullName": "Blaise Diagne International Airport", "country": "Senegal"},
    {"code": "ABJ", "name": "Abidjan", "fullName": "Félix-Houphouët-Boigny International Airport", "country": "Ivory Coast"},
    {"code": "LFW", "name": "Lome", "fullName": "Gnassingbé Eyadéma International Airport", "country": "Togo"},
    {"code": "COO", "name": "Cotonou", "fullName": "Cadjehoun Airport", "country": "Benin"},
    {"code": "OUA", "name": "Ouagadougou", "fullName": "Ouagadougou Airport", "country": "Burkina Faso"},
    {"code": "BKO", "name": "Bamako", "fullName": "Modibo Keita International Airport", "country": "Mali"},
    {"code": "CKY", "name": "Conakry", "fullName": "Conakry International Airport", "country": "Guinea"},
    {"code": "FNA", "name": "Freetown", "fullName": "Lungi International Airport", "country": "Sierra Leone"},
    {"code": "ROB", "name": "Monrovia", "fullName": "Roberts International Airport", "country": "Liberia"},
    {"code": "BJL", "name": "Banjul", "fullName": "Banjul International Airport", "country": "Gambia"},
    {"code": "OXB", "name": "Bissau", "fullName": "Osvaldo Vieira International Airport", "country": "Guinea-Bissau"},
    {"code": "NIM", "name": "Niamey", "fullName": "Diori Hamani International Airport", "country": "Niger"},
    {"code": "NDJ", "name": "N'Djamena", "fullName": "N'Djamena International Airport", "country": "Chad"},
    {"code": "RAI", "name": "Praia", "fullName": "Nelson Mandela International Airport", "country": "Cape Verde"},
    {"code": "SID", "name": "Sal", "fullName": "Amílcar Cabral International Airport", "country": "Cape Verde"},
    {"code": "NKC", "name": "Nouakchott", "fullName": "Nouakchott International Airport", "country": "Mauritania"},

    # ============ EAST AFRICA ============
    {"code": "NBO", "name": "Nairobi", "fullName": "Jomo Kenyatta International Airport", "country": "Kenya"},
    {"code": "MBA", "name": "Mombasa", "fullName": "Moi International Airport", "country": "Kenya"},
    {"code": "KIS", "name": "Kisumu", "fullName": "Kisumu International Airport", "country": "Kenya"},
    {"code": "ADD", "name": "Addis Ababa", "fullName": "Bole International Airport", "country": "Ethiopia"},
    {"code": "DAR", "name": "Dar es Salaam", "fullName": "Julius Nyerere International Airport", "country": "Tanzania"},
    {"code": "JRO", "name": "Kilimanjaro", "fullName": "Kilimanjaro International Airport", "country": "Tanzania"},
    {"code": "ZNZ", "name": "Zanzibar", "fullName": "Abeid Amani Karume International Airport", "country": "Tanzania"},
    {"code": "EBB", "name": "Entebbe", "fullName": "Entebbe International Airport", "country": "Uganda"},
    {"code": "KGL", "name": "Kigali", "fullName": "Kigali International Airport", "country": "Rwanda"},
    {"code": "BJM", "name": "Bujumbura", "fullName": "Bujumbura International Airport", "country": "Burundi"},
    {"code": "MGQ", "name": "Mogadishu", "fullName": "Aden Adde International Airport", "country": "Somalia"},
    {"code": "JIB", "name": "Djibouti", "fullName": "Djibouti–Ambouli International Airport", "country": "Djibouti"},
    {"code": "ASM", "name": "Asmara", "fullName": "Asmara International Airport", "country": "Eritrea"},
    {"code": "SEZ", "name": "Mahe", "fullName": "Seychelles International Airport", "country": "Seychelles"},
    {"code": "MRU", "name": "Mauritius", "fullName": "Sir Seewoosagur Ramgoolam International Airport", "country": "Mauritius"},
    {"code": "RUN", "name": "Reunion", "fullName": "Roland Garros Airport", "country": "Reunion"},
    {"code": "TNR", "name": "Antananarivo", "fullName": "Ivato International Airport", "country": "Madagascar"},
    {"code": "MLE", "name": "Male", "fullName": "Velana International Airport", "country": "Maldives"},

    # ============ SOUTHERN AFRICA ============
    {"code": "JNB", "name": "Johannesburg", "fullName": "OR Tambo International Airport", "country": "South Africa"},
    {"code": "CPT", "name": "Cape Town", "fullName": "Cape Town International Airport", "country": "South Africa"},
    {"code": "DUR", "name": "Durban", "fullName": "King Shaka International Airport", "country": "South Africa"},
    {"code": "PLZ", "name": "Port Elizabeth", "fullName": "Chief Dawid Stuurman International Airport", "country": "South Africa"},
    {"code": "BFN", "name": "Bloemfontein", "fullName": "Bram Fischer International Airport", "country": "South Africa"},
    {"code": "HRE", "name": "Harare", "fullName": "Robert Gabriel Mugabe International Airport", "country": "Zimbabwe"},
    {"code": "VFA", "name": "Victoria Falls", "fullName": "Victoria Falls International Airport", "country": "Zimbabwe"},
    {"code": "BUQ", "name": "Bulawayo", "fullName": "Joshua Mqabuko Nkomo International Airport", "country": "Zimbabwe"},
    {"code": "LUN", "name": "Lusaka", "fullName": "Kenneth Kaunda International Airport", "country": "Zambia"},
    {"code": "LVI", "name": "Livingstone", "fullName": "Harry Mwanga Nkumbula International Airport", "country": "Zambia"},
    {"code": "NLA", "name": "Ndola", "fullName": "Simon Mwansa Kapwepwe International Airport", "country": "Zambia"},
    {"code": "LLW", "name": "Lilongwe", "fullName": "Kamuzu International Airport", "country": "Malawi"},
    {"code": "BLZ", "name": "Blantyre", "fullName": "Chileka International Airport", "country": "Malawi"},
    {"code": "MPM", "name": "Maputo", "fullName": "Maputo International Airport", "country": "Mozambique"},
    {"code": "BEW", "name": "Beira", "fullName": "Beira Airport", "country": "Mozambique"},
    {"code": "GBE", "name": "Gaborone", "fullName": "Sir Seretse Khama International Airport", "country": "Botswana"},
    {"code": "MUN", "name": "Maun", "fullName": "Maun Airport", "country": "Botswana"},
    {"code": "WDH", "name": "Windhoek", "fullName": "Hosea Kutako International Airport", "country": "Namibia"},
    {"code": "LAD", "name": "Luanda", "fullName": "Quatro de Fevereiro International Airport", "country": "Angola"},
    {"code": "FIH", "name": "Kinshasa", "fullName": "N'djili International Airport", "country": "DR Congo"},
    {"code": "FBM", "name": "Lubumbashi", "fullName": "Lubumbashi International Airport", "country": "DR Congo"},
    {"code": "LBV", "name": "Libreville", "fullName": "Libreville International Airport", "country": "Gabon"},
    {"code": "DLA", "name": "Douala", "fullName": "Douala International Airport", "country": "Cameroon"},
    {"code": "NSI", "name": "Yaounde", "fullName": "Yaoundé Nsimalen International Airport", "country": "Cameroon"},
    {"code": "SSG", "name": "Malabo", "fullName": "Malabo International Airport", "country": "Equatorial Guinea"},
    {"code": "BZV", "name": "Brazzaville", "fullName": "Maya-Maya Airport", "country": "Congo"},
    {"code": "PNR", "name": "Pointe-Noire", "fullName": "Agostinho-Neto International Airport", "country": "Congo"},
    {"code": "BGF", "name": "Bangui", "fullName": "Bangui M'Poko International Airport", "country": "Central African Republic"},
    {"code": "SZG", "name": "Sao Tome", "fullName": "São Tomé International Airport", "country": "Sao Tome"},

    # ============ NORTH AFRICA ============
    {"code": "CAI", "name": "Cairo", "fullName": "Cairo International Airport", "country": "Egypt"},
    {"code": "HRG", "name": "Hurghada", "fullName": "Hurghada International Airport", "country": "Egypt"},
    {"code": "SSH", "name": "Sharm El Sheikh", "fullName": "Sharm el-Sheikh International Airport", "country": "Egypt"},
    {"code": "LXR", "name": "Luxor", "fullName": "Luxor International Airport", "country": "Egypt"},
    {"code": "ASW", "name": "Aswan", "fullName": "Aswan International Airport", "country": "Egypt"},
    {"code": "ALY", "name": "Alexandria", "fullName": "Borg El Arab Airport", "country": "Egypt"},
    {"code": "CMN", "name": "Casablanca", "fullName": "Mohammed V International Airport", "country": "Morocco"},
    {"code": "RAK", "name": "Marrakech", "fullName": "Marrakech Menara Airport", "country": "Morocco"},
    {"code": "AGA", "name": "Agadir", "fullName": "Agadir–Al Massira Airport", "country": "Morocco"},
    {"code": "FEZ", "name": "Fez", "fullName": "Fès–Saïs Airport", "country": "Morocco"},
    {"code": "TNG", "name": "Tangier", "fullName": "Tangier Ibn Battouta Airport", "country": "Morocco"},
    {"code": "ALG", "name": "Algiers", "fullName": "Houari Boumediene Airport", "country": "Algeria"},
    {"code": "ORN", "name": "Oran", "fullName": "Ahmed Ben Bella Airport", "country": "Algeria"},
    {"code": "TUN", "name": "Tunis", "fullName": "Tunis–Carthage International Airport", "country": "Tunisia"},
    {"code": "DJE", "name": "Djerba", "fullName": "Djerba–Zarzis International Airport", "country": "Tunisia"},
    {"code": "TIP", "name": "Tripoli", "fullName": "Mitiga International Airport", "country": "Libya"},
    {"code": "BEN", "name": "Benghazi", "fullName": "Benina International Airport", "country": "Libya"},
    {"code": "KRT", "name": "Khartoum", "fullName": "Khartoum International Airport", "country": "Sudan"},

    # ============ MIDDLE EAST ============
    {"code": "DXB", "name": "Dubai", "fullName": "Dubai International Airport", "country": "UAE"},
    {"code": "DWC", "name": "Dubai World Central", "fullName": "Al Maktoum International Airport", "country": "UAE"},
    {"code": "AUH", "name": "Abu Dhabi", "fullName": "Abu Dhabi International Airport", "country": "UAE"},
    {"code": "SHJ", "name": "Sharjah", "fullName": "Sharjah International Airport", "country": "UAE"},
    {"code": "DOH", "name": "Doha", "fullName": "Hamad International Airport", "country": "Qatar"},
    {"code": "BAH", "name": "Bahrain", "fullName": "Bahrain International Airport", "country": "Bahrain"},
    {"code": "KWI", "name": "Kuwait City", "fullName": "Kuwait International Airport", "country": "Kuwait"},
    {"code": "MCT", "name": "Muscat", "fullName": "Muscat International Airport", "country": "Oman"},
    {"code": "SLL", "name": "Salalah", "fullName": "Salalah Airport", "country": "Oman"},
    {"code": "JED", "name": "Jeddah", "fullName": "King Abdulaziz International Airport", "country": "Saudi Arabia"},
    {"code": "RUH", "name": "Riyadh", "fullName": "King Khalid International Airport", "country": "Saudi Arabia"},
    {"code": "DMM", "name": "Dammam", "fullName": "King Fahd International Airport", "country": "Saudi Arabia"},
    {"code": "MED", "name": "Medina", "fullName": "Prince Mohammad Bin Abdulaziz Airport", "country": "Saudi Arabia"},
    {"code": "AMM", "name": "Amman", "fullName": "Queen Alia International Airport", "country": "Jordan"},
    {"code": "AQJ", "name": "Aqaba", "fullName": "King Hussein International Airport", "country": "Jordan"},
    {"code": "TLV", "name": "Tel Aviv", "fullName": "Ben Gurion Airport", "country": "Israel"},
    {"code": "BEY", "name": "Beirut", "fullName": "Rafic Hariri International Airport", "country": "Lebanon"},
    {"code": "DAM", "name": "Damascus", "fullName": "Damascus International Airport", "country": "Syria"},
    {"code": "BGW", "name": "Baghdad", "fullName": "Baghdad International Airport", "country": "Iraq"},
    {"code": "BSR", "name": "Basra", "fullName": "Basra International Airport", "country": "Iraq"},
    {"code": "EBL", "name": "Erbil", "fullName": "Erbil International Airport", "country": "Iraq"},
    {"code": "IKA", "name": "Tehran", "fullName": "Imam Khomeini International Airport", "country": "Iran"},
    {"code": "MHD", "name": "Mashhad", "fullName": "Mashhad International Airport", "country": "Iran"},
    {"code": "SYZ", "name": "Shiraz", "fullName": "Shiraz International Airport", "country": "Iran"},
    {"code": "ISF", "name": "Isfahan", "fullName": "Isfahan International Airport", "country": "Iran"},
    {"code": "AYT", "name": "Antalya", "fullName": "Antalya Airport", "country": "Turkey"},
    {"code": "IST", "name": "Istanbul", "fullName": "Istanbul Airport", "country": "Turkey"},
    {"code": "SAW", "name": "Istanbul Sabiha", "fullName": "Sabiha Gökçen International Airport", "country": "Turkey"},
    {"code": "ADB", "name": "Izmir", "fullName": "Adnan Menderes Airport", "country": "Turkey"},
    {"code": "ESB", "name": "Ankara", "fullName": "Esenboğa International Airport", "country": "Turkey"},
    {"code": "DLM", "name": "Dalaman", "fullName": "Dalaman Airport", "country": "Turkey"},
    {"code": "BJV", "name": "Bodrum", "fullName": "Bodrum Airport", "country": "Turkey"},

    # ============ EUROPE - UK & IRELAND ============
    {"code": "LHR", "name": "London Heathrow", "fullName": "Heathrow Airport", "country": "UK"},
    {"code": "LGW", "name": "London Gatwick", "fullName": "Gatwick Airport", "country": "UK"},
    {"code": "STN", "name": "London Stansted", "fullName": "Stansted Airport", "country": "UK"},
    {"code": "LTN", "name": "London Luton", "fullName": "Luton Airport", "country": "UK"},
    {"code": "LCY", "name": "London City", "fullName": "London City Airport", "country": "UK"},
    {"code": "MAN", "name": "Manchester", "fullName": "Manchester Airport", "country": "UK"},
    {"code": "BHX", "name": "Birmingham", "fullName": "Birmingham Airport", "country": "UK"},
    {"code": "EDI", "name": "Edinburgh", "fullName": "Edinburgh Airport", "country": "UK"},
    {"code": "GLA", "name": "Glasgow", "fullName": "Glasgow Airport", "country": "UK"},
    {"code": "BRS", "name": "Bristol", "fullName": "Bristol Airport", "country": "UK"},
    {"code": "NCL", "name": "Newcastle", "fullName": "Newcastle Airport", "country": "UK"},
    {"code": "LPL", "name": "Liverpool", "fullName": "Liverpool John Lennon Airport", "country": "UK"},
    {"code": "LBA", "name": "Leeds", "fullName": "Leeds Bradford Airport", "country": "UK"},
    {"code": "ABZ", "name": "Aberdeen", "fullName": "Aberdeen Airport", "country": "UK"},
    {"code": "BFS", "name": "Belfast", "fullName": "Belfast International Airport", "country": "UK"},
    {"code": "CWL", "name": "Cardiff", "fullName": "Cardiff Airport", "country": "UK"},
    {"code": "DUB", "name": "Dublin", "fullName": "Dublin Airport", "country": "Ireland"},
    {"code": "SNN", "name": "Shannon", "fullName": "Shannon Airport", "country": "Ireland"},
    {"code": "ORK", "name": "Cork", "fullName": "Cork Airport", "country": "Ireland"},

    # ============ EUROPE - WESTERN ============
    {"code": "CDG", "name": "Paris CDG", "fullName": "Charles de Gaulle Airport", "country": "France"},
    {"code": "ORY", "name": "Paris Orly", "fullName": "Orly Airport", "country": "France"},
    {"code": "NCE", "name": "Nice", "fullName": "Nice Côte d'Azur Airport", "country": "France"},
    {"code": "LYS", "name": "Lyon", "fullName": "Lyon–Saint-Exupéry Airport", "country": "France"},
    {"code": "MRS", "name": "Marseille", "fullName": "Marseille Provence Airport", "country": "France"},
    {"code": "TLS", "name": "Toulouse", "fullName": "Toulouse–Blagnac Airport", "country": "France"},
    {"code": "BOD", "name": "Bordeaux", "fullName": "Bordeaux–Mérignac Airport", "country": "France"},
    {"code": "NTE", "name": "Nantes", "fullName": "Nantes Atlantique Airport", "country": "France"},
    {"code": "FRA", "name": "Frankfurt", "fullName": "Frankfurt Airport", "country": "Germany"},
    {"code": "MUC", "name": "Munich", "fullName": "Munich Airport", "country": "Germany"},
    {"code": "DUS", "name": "Dusseldorf", "fullName": "Düsseldorf Airport", "country": "Germany"},
    {"code": "TXL", "name": "Berlin", "fullName": "Berlin Brandenburg Airport", "country": "Germany"},
    {"code": "BER", "name": "Berlin Brandenburg", "fullName": "Berlin Brandenburg Airport", "country": "Germany"},
    {"code": "HAM", "name": "Hamburg", "fullName": "Hamburg Airport", "country": "Germany"},
    {"code": "STR", "name": "Stuttgart", "fullName": "Stuttgart Airport", "country": "Germany"},
    {"code": "CGN", "name": "Cologne", "fullName": "Cologne Bonn Airport", "country": "Germany"},
    {"code": "HAJ", "name": "Hanover", "fullName": "Hannover Airport", "country": "Germany"},
    {"code": "NUE", "name": "Nuremberg", "fullName": "Nuremberg Airport", "country": "Germany"},
    {"code": "AMS", "name": "Amsterdam", "fullName": "Schiphol Airport", "country": "Netherlands"},
    {"code": "RTM", "name": "Rotterdam", "fullName": "Rotterdam The Hague Airport", "country": "Netherlands"},
    {"code": "EIN", "name": "Eindhoven", "fullName": "Eindhoven Airport", "country": "Netherlands"},
    {"code": "BRU", "name": "Brussels", "fullName": "Brussels Airport", "country": "Belgium"},
    {"code": "CRL", "name": "Brussels South", "fullName": "Brussels South Charleroi Airport", "country": "Belgium"},
    {"code": "LUX", "name": "Luxembourg", "fullName": "Luxembourg Airport", "country": "Luxembourg"},
    {"code": "ZRH", "name": "Zurich", "fullName": "Zurich Airport", "country": "Switzerland"},
    {"code": "GVA", "name": "Geneva", "fullName": "Geneva Airport", "country": "Switzerland"},
    {"code": "BSL", "name": "Basel", "fullName": "EuroAirport Basel Mulhouse Freiburg", "country": "Switzerland"},
    {"code": "VIE", "name": "Vienna", "fullName": "Vienna International Airport", "country": "Austria"},
    {"code": "SZG", "name": "Salzburg", "fullName": "Salzburg Airport", "country": "Austria"},
    {"code": "INN", "name": "Innsbruck", "fullName": "Innsbruck Airport", "country": "Austria"},

    # ============ EUROPE - SOUTHERN ============
    {"code": "MAD", "name": "Madrid", "fullName": "Adolfo Suárez Madrid–Barajas Airport", "country": "Spain"},
    {"code": "BCN", "name": "Barcelona", "fullName": "Barcelona–El Prat Airport", "country": "Spain"},
    {"code": "PMI", "name": "Palma de Mallorca", "fullName": "Palma de Mallorca Airport", "country": "Spain"},
    {"code": "AGP", "name": "Malaga", "fullName": "Málaga–Costa del Sol Airport", "country": "Spain"},
    {"code": "ALC", "name": "Alicante", "fullName": "Alicante–Elche Airport", "country": "Spain"},
    {"code": "VLC", "name": "Valencia", "fullName": "Valencia Airport", "country": "Spain"},
    {"code": "SVQ", "name": "Seville", "fullName": "Seville Airport", "country": "Spain"},
    {"code": "BIO", "name": "Bilbao", "fullName": "Bilbao Airport", "country": "Spain"},
    {"code": "TFS", "name": "Tenerife South", "fullName": "Tenerife South Airport", "country": "Spain"},
    {"code": "LPA", "name": "Gran Canaria", "fullName": "Gran Canaria Airport", "country": "Spain"},
    {"code": "FUE", "name": "Fuerteventura", "fullName": "Fuerteventura Airport", "country": "Spain"},
    {"code": "ACE", "name": "Lanzarote", "fullName": "Lanzarote Airport", "country": "Spain"},
    {"code": "IBZ", "name": "Ibiza", "fullName": "Ibiza Airport", "country": "Spain"},
    {"code": "LIS", "name": "Lisbon", "fullName": "Humberto Delgado Airport", "country": "Portugal"},
    {"code": "OPO", "name": "Porto", "fullName": "Francisco Sá Carneiro Airport", "country": "Portugal"},
    {"code": "FAO", "name": "Faro", "fullName": "Faro Airport", "country": "Portugal"},
    {"code": "FNC", "name": "Funchal", "fullName": "Madeira Airport", "country": "Portugal"},
    {"code": "FCO", "name": "Rome Fiumicino", "fullName": "Leonardo da Vinci International Airport", "country": "Italy"},
    {"code": "CIA", "name": "Rome Ciampino", "fullName": "Ciampino Airport", "country": "Italy"},
    {"code": "MXP", "name": "Milan Malpensa", "fullName": "Milan Malpensa Airport", "country": "Italy"},
    {"code": "LIN", "name": "Milan Linate", "fullName": "Milan Linate Airport", "country": "Italy"},
    {"code": "BGY", "name": "Milan Bergamo", "fullName": "Il Caravaggio International Airport", "country": "Italy"},
    {"code": "VCE", "name": "Venice", "fullName": "Venice Marco Polo Airport", "country": "Italy"},
    {"code": "NAP", "name": "Naples", "fullName": "Naples International Airport", "country": "Italy"},
    {"code": "BLQ", "name": "Bologna", "fullName": "Bologna Airport", "country": "Italy"},
    {"code": "FLR", "name": "Florence", "fullName": "Florence Airport", "country": "Italy"},
    {"code": "PSA", "name": "Pisa", "fullName": "Pisa International Airport", "country": "Italy"},
    {"code": "CTA", "name": "Catania", "fullName": "Catania–Fontanarossa Airport", "country": "Italy"},
    {"code": "PMO", "name": "Palermo", "fullName": "Falcone–Borsellino Airport", "country": "Italy"},
    {"code": "BRI", "name": "Bari", "fullName": "Bari Airport", "country": "Italy"},
    {"code": "TRN", "name": "Turin", "fullName": "Turin Airport", "country": "Italy"},
    {"code": "GOA", "name": "Genoa", "fullName": "Genoa Cristoforo Colombo Airport", "country": "Italy"},
    {"code": "ATH", "name": "Athens", "fullName": "Athens International Airport", "country": "Greece"},
    {"code": "SKG", "name": "Thessaloniki", "fullName": "Thessaloniki Airport", "country": "Greece"},
    {"code": "HER", "name": "Heraklion", "fullName": "Heraklion International Airport", "country": "Greece"},
    {"code": "RHO", "name": "Rhodes", "fullName": "Rhodes International Airport", "country": "Greece"},
    {"code": "CHQ", "name": "Chania", "fullName": "Chania International Airport", "country": "Greece"},
    {"code": "CFU", "name": "Corfu", "fullName": "Corfu International Airport", "country": "Greece"},
    {"code": "KGS", "name": "Kos", "fullName": "Kos Island International Airport", "country": "Greece"},
    {"code": "JMK", "name": "Mykonos", "fullName": "Mykonos Airport", "country": "Greece"},
    {"code": "JTR", "name": "Santorini", "fullName": "Santorini Airport", "country": "Greece"},
    {"code": "ZTH", "name": "Zakynthos", "fullName": "Zakynthos International Airport", "country": "Greece"},

    # ============ EUROPE - NORTHERN ============
    {"code": "CPH", "name": "Copenhagen", "fullName": "Copenhagen Airport", "country": "Denmark"},
    {"code": "BLL", "name": "Billund", "fullName": "Billund Airport", "country": "Denmark"},
    {"code": "ARN", "name": "Stockholm Arlanda", "fullName": "Stockholm Arlanda Airport", "country": "Sweden"},
    {"code": "GOT", "name": "Gothenburg", "fullName": "Gothenburg Landvetter Airport", "country": "Sweden"},
    {"code": "OSL", "name": "Oslo", "fullName": "Oslo Gardermoen Airport", "country": "Norway"},
    {"code": "BGO", "name": "Bergen", "fullName": "Bergen Airport", "country": "Norway"},
    {"code": "TRD", "name": "Trondheim", "fullName": "Trondheim Airport", "country": "Norway"},
    {"code": "SVG", "name": "Stavanger", "fullName": "Stavanger Airport", "country": "Norway"},
    {"code": "HEL", "name": "Helsinki", "fullName": "Helsinki Airport", "country": "Finland"},
    {"code": "TMP", "name": "Tampere", "fullName": "Tampere–Pirkkala Airport", "country": "Finland"},
    {"code": "KEF", "name": "Reykjavik", "fullName": "Keflavík International Airport", "country": "Iceland"},

    # ============ EUROPE - EASTERN ============
    {"code": "WAW", "name": "Warsaw", "fullName": "Warsaw Chopin Airport", "country": "Poland"},
    {"code": "WMI", "name": "Warsaw Modlin", "fullName": "Warsaw Modlin Airport", "country": "Poland"},
    {"code": "KRK", "name": "Krakow", "fullName": "Krakow John Paul II International Airport", "country": "Poland"},
    {"code": "GDN", "name": "Gdansk", "fullName": "Gdańsk Lech Wałęsa Airport", "country": "Poland"},
    {"code": "WRO", "name": "Wroclaw", "fullName": "Wrocław Airport", "country": "Poland"},
    {"code": "PRG", "name": "Prague", "fullName": "Václav Havel Airport Prague", "country": "Czech Republic"},
    {"code": "BRQ", "name": "Brno", "fullName": "Brno–Tuřany Airport", "country": "Czech Republic"},
    {"code": "BUD", "name": "Budapest", "fullName": "Budapest Ferenc Liszt International Airport", "country": "Hungary"},
    {"code": "OTP", "name": "Bucharest", "fullName": "Henri Coandă International Airport", "country": "Romania"},
    {"code": "CLJ", "name": "Cluj-Napoca", "fullName": "Cluj International Airport", "country": "Romania"},
    {"code": "TSR", "name": "Timisoara", "fullName": "Timișoara Traian Vuia International Airport", "country": "Romania"},
    {"code": "SOF", "name": "Sofia", "fullName": "Sofia Airport", "country": "Bulgaria"},
    {"code": "VAR", "name": "Varna", "fullName": "Varna Airport", "country": "Bulgaria"},
    {"code": "BOJ", "name": "Burgas", "fullName": "Burgas Airport", "country": "Bulgaria"},
    {"code": "BEG", "name": "Belgrade", "fullName": "Belgrade Nikola Tesla Airport", "country": "Serbia"},
    {"code": "ZAG", "name": "Zagreb", "fullName": "Franjo Tuđman Airport", "country": "Croatia"},
    {"code": "SPU", "name": "Split", "fullName": "Split Airport", "country": "Croatia"},
    {"code": "DBV", "name": "Dubrovnik", "fullName": "Dubrovnik Airport", "country": "Croatia"},
    {"code": "PUY", "name": "Pula", "fullName": "Pula Airport", "country": "Croatia"},
    {"code": "LJU", "name": "Ljubljana", "fullName": "Ljubljana Jože Pučnik Airport", "country": "Slovenia"},
    {"code": "SJJ", "name": "Sarajevo", "fullName": "Sarajevo International Airport", "country": "Bosnia"},
    {"code": "TGD", "name": "Podgorica", "fullName": "Podgorica Airport", "country": "Montenegro"},
    {"code": "TIV", "name": "Tivat", "fullName": "Tivat Airport", "country": "Montenegro"},
    {"code": "SKP", "name": "Skopje", "fullName": "Skopje International Airport", "country": "North Macedonia"},
    {"code": "TIA", "name": "Tirana", "fullName": "Tirana International Airport", "country": "Albania"},
    {"code": "KIV", "name": "Chisinau", "fullName": "Chișinău International Airport", "country": "Moldova"},
    {"code": "KBP", "name": "Kyiv Boryspil", "fullName": "Boryspil International Airport", "country": "Ukraine"},
    {"code": "IEV", "name": "Kyiv Zhuliany", "fullName": "Kyiv International Airport", "country": "Ukraine"},
    {"code": "ODS", "name": "Odessa", "fullName": "Odessa International Airport", "country": "Ukraine"},
    {"code": "LWO", "name": "Lviv", "fullName": "Lviv Danylo Halytskyi International Airport", "country": "Ukraine"},
    {"code": "MSQ", "name": "Minsk", "fullName": "Minsk National Airport", "country": "Belarus"},
    {"code": "RIX", "name": "Riga", "fullName": "Riga International Airport", "country": "Latvia"},
    {"code": "VNO", "name": "Vilnius", "fullName": "Vilnius International Airport", "country": "Lithuania"},
    {"code": "KUN", "name": "Kaunas", "fullName": "Kaunas Airport", "country": "Lithuania"},
    {"code": "TLL", "name": "Tallinn", "fullName": "Tallinn Airport", "country": "Estonia"},

    # ============ RUSSIA & CIS ============
    {"code": "SVO", "name": "Moscow Sheremetyevo", "fullName": "Sheremetyevo International Airport", "country": "Russia"},
    {"code": "DME", "name": "Moscow Domodedovo", "fullName": "Domodedovo International Airport", "country": "Russia"},
    {"code": "VKO", "name": "Moscow Vnukovo", "fullName": "Vnukovo International Airport", "country": "Russia"},
    {"code": "LED", "name": "St Petersburg", "fullName": "Pulkovo Airport", "country": "Russia"},
    {"code": "AER", "name": "Sochi", "fullName": "Sochi International Airport", "country": "Russia"},
    {"code": "KZN", "name": "Kazan", "fullName": "Kazan International Airport", "country": "Russia"},
    {"code": "SVX", "name": "Yekaterinburg", "fullName": "Koltsovo Airport", "country": "Russia"},
    {"code": "OVB", "name": "Novosibirsk", "fullName": "Tolmachevo Airport", "country": "Russia"},
    {"code": "VVO", "name": "Vladivostok", "fullName": "Vladivostok International Airport", "country": "Russia"},
    {"code": "GYD", "name": "Baku", "fullName": "Heydar Aliyev International Airport", "country": "Azerbaijan"},
    {"code": "TBS", "name": "Tbilisi", "fullName": "Tbilisi International Airport", "country": "Georgia"},
    {"code": "BUS", "name": "Batumi", "fullName": "Batumi International Airport", "country": "Georgia"},
    {"code": "EVN", "name": "Yerevan", "fullName": "Zvartnots International Airport", "country": "Armenia"},
    {"code": "ALA", "name": "Almaty", "fullName": "Almaty International Airport", "country": "Kazakhstan"},
    {"code": "NQZ", "name": "Astana", "fullName": "Nursultan Nazarbayev International Airport", "country": "Kazakhstan"},
    {"code": "TAS", "name": "Tashkent", "fullName": "Islam Karimov Tashkent International Airport", "country": "Uzbekistan"},
    {"code": "FRU", "name": "Bishkek", "fullName": "Manas International Airport", "country": "Kyrgyzstan"},
    {"code": "DYU", "name": "Dushanbe", "fullName": "Dushanbe International Airport", "country": "Tajikistan"},
    {"code": "ASB", "name": "Ashgabat", "fullName": "Ashgabat International Airport", "country": "Turkmenistan"},

    # ============ NORTH AMERICA - USA ============
    {"code": "JFK", "name": "New York JFK", "fullName": "John F. Kennedy International Airport", "country": "USA"},
    {"code": "EWR", "name": "Newark", "fullName": "Newark Liberty International Airport", "country": "USA"},
    {"code": "LGA", "name": "New York LaGuardia", "fullName": "LaGuardia Airport", "country": "USA"},
    {"code": "LAX", "name": "Los Angeles", "fullName": "Los Angeles International Airport", "country": "USA"},
    {"code": "SFO", "name": "San Francisco", "fullName": "San Francisco International Airport", "country": "USA"},
    {"code": "OAK", "name": "Oakland", "fullName": "Oakland International Airport", "country": "USA"},
    {"code": "SJC", "name": "San Jose", "fullName": "San José International Airport", "country": "USA"},
    {"code": "ORD", "name": "Chicago O'Hare", "fullName": "O'Hare International Airport", "country": "USA"},
    {"code": "MDW", "name": "Chicago Midway", "fullName": "Chicago Midway International Airport", "country": "USA"},
    {"code": "ATL", "name": "Atlanta", "fullName": "Hartsfield-Jackson Atlanta International Airport", "country": "USA"},
    {"code": "DFW", "name": "Dallas/Fort Worth", "fullName": "Dallas/Fort Worth International Airport", "country": "USA"},
    {"code": "DAL", "name": "Dallas Love Field", "fullName": "Dallas Love Field", "country": "USA"},
    {"code": "IAH", "name": "Houston Intercontinental", "fullName": "George Bush Intercontinental Airport", "country": "USA"},
    {"code": "HOU", "name": "Houston Hobby", "fullName": "William P. Hobby Airport", "country": "USA"},
    {"code": "MIA", "name": "Miami", "fullName": "Miami International Airport", "country": "USA"},
    {"code": "FLL", "name": "Fort Lauderdale", "fullName": "Fort Lauderdale–Hollywood International Airport", "country": "USA"},
    {"code": "MCO", "name": "Orlando", "fullName": "Orlando International Airport", "country": "USA"},
    {"code": "TPA", "name": "Tampa", "fullName": "Tampa International Airport", "country": "USA"},
    {"code": "PBI", "name": "West Palm Beach", "fullName": "Palm Beach International Airport", "country": "USA"},
    {"code": "JAX", "name": "Jacksonville", "fullName": "Jacksonville International Airport", "country": "USA"},
    {"code": "BOS", "name": "Boston", "fullName": "Logan International Airport", "country": "USA"},
    {"code": "PHL", "name": "Philadelphia", "fullName": "Philadelphia International Airport", "country": "USA"},
    {"code": "DCA", "name": "Washington Reagan", "fullName": "Ronald Reagan Washington National Airport", "country": "USA"},
    {"code": "IAD", "name": "Washington Dulles", "fullName": "Washington Dulles International Airport", "country": "USA"},
    {"code": "BWI", "name": "Baltimore", "fullName": "Baltimore/Washington International Airport", "country": "USA"},
    {"code": "DEN", "name": "Denver", "fullName": "Denver International Airport", "country": "USA"},
    {"code": "PHX", "name": "Phoenix", "fullName": "Phoenix Sky Harbor International Airport", "country": "USA"},
    {"code": "SEA", "name": "Seattle", "fullName": "Seattle-Tacoma International Airport", "country": "USA"},
    {"code": "PDX", "name": "Portland", "fullName": "Portland International Airport", "country": "USA"},
    {"code": "SAN", "name": "San Diego", "fullName": "San Diego International Airport", "country": "USA"},
    {"code": "LAS", "name": "Las Vegas", "fullName": "Harry Reid International Airport", "country": "USA"},
    {"code": "MSP", "name": "Minneapolis", "fullName": "Minneapolis–Saint Paul International Airport", "country": "USA"},
    {"code": "DTW", "name": "Detroit", "fullName": "Detroit Metropolitan Wayne County Airport", "country": "USA"},
    {"code": "CLT", "name": "Charlotte", "fullName": "Charlotte Douglas International Airport", "country": "USA"},
    {"code": "RDU", "name": "Raleigh-Durham", "fullName": "Raleigh-Durham International Airport", "country": "USA"},
    {"code": "BNA", "name": "Nashville", "fullName": "Nashville International Airport", "country": "USA"},
    {"code": "AUS", "name": "Austin", "fullName": "Austin-Bergstrom International Airport", "country": "USA"},
    {"code": "SAT", "name": "San Antonio", "fullName": "San Antonio International Airport", "country": "USA"},
    {"code": "MCI", "name": "Kansas City", "fullName": "Kansas City International Airport", "country": "USA"},
    {"code": "STL", "name": "St Louis", "fullName": "St. Louis Lambert International Airport", "country": "USA"},
    {"code": "CVG", "name": "Cincinnati", "fullName": "Cincinnati/Northern Kentucky International Airport", "country": "USA"},
    {"code": "CMH", "name": "Columbus", "fullName": "John Glenn Columbus International Airport", "country": "USA"},
    {"code": "CLE", "name": "Cleveland", "fullName": "Cleveland Hopkins International Airport", "country": "USA"},
    {"code": "PIT", "name": "Pittsburgh", "fullName": "Pittsburgh International Airport", "country": "USA"},
    {"code": "IND", "name": "Indianapolis", "fullName": "Indianapolis International Airport", "country": "USA"},
    {"code": "SLC", "name": "Salt Lake City", "fullName": "Salt Lake City International Airport", "country": "USA"},
    {"code": "HNL", "name": "Honolulu", "fullName": "Daniel K. Inouye International Airport", "country": "USA"},
    {"code": "OGG", "name": "Maui", "fullName": "Kahului Airport", "country": "USA"},
    {"code": "KOA", "name": "Kona", "fullName": "Ellison Onizuka Kona International Airport", "country": "USA"},
    {"code": "ANC", "name": "Anchorage", "fullName": "Ted Stevens Anchorage International Airport", "country": "USA"},
    {"code": "MSY", "name": "New Orleans", "fullName": "Louis Armstrong New Orleans International Airport", "country": "USA"},
    {"code": "MKE", "name": "Milwaukee", "fullName": "General Mitchell International Airport", "country": "USA"},
    {"code": "SMF", "name": "Sacramento", "fullName": "Sacramento International Airport", "country": "USA"},
    {"code": "SNA", "name": "Orange County", "fullName": "John Wayne Airport", "country": "USA"},
    {"code": "BUR", "name": "Burbank", "fullName": "Hollywood Burbank Airport", "country": "USA"},
    {"code": "ONT", "name": "Ontario", "fullName": "Ontario International Airport", "country": "USA"},
    {"code": "RNO", "name": "Reno", "fullName": "Reno-Tahoe International Airport", "country": "USA"},
    {"code": "ABQ", "name": "Albuquerque", "fullName": "Albuquerque International Sunport", "country": "USA"},
    {"code": "TUS", "name": "Tucson", "fullName": "Tucson International Airport", "country": "USA"},
    {"code": "ELP", "name": "El Paso", "fullName": "El Paso International Airport", "country": "USA"},
    {"code": "OKC", "name": "Oklahoma City", "fullName": "Will Rogers World Airport", "country": "USA"},
    {"code": "TUL", "name": "Tulsa", "fullName": "Tulsa International Airport", "country": "USA"},
    {"code": "OMA", "name": "Omaha", "fullName": "Eppley Airfield", "country": "USA"},
    {"code": "MEM", "name": "Memphis", "fullName": "Memphis International Airport", "country": "USA"},
    {"code": "BDL", "name": "Hartford", "fullName": "Bradley International Airport", "country": "USA"},
    {"code": "PVD", "name": "Providence", "fullName": "T. F. Green International Airport", "country": "USA"},
    {"code": "RIC", "name": "Richmond", "fullName": "Richmond International Airport", "country": "USA"},
    {"code": "ORF", "name": "Norfolk", "fullName": "Norfolk International Airport", "country": "USA"},
    {"code": "BUF", "name": "Buffalo", "fullName": "Buffalo Niagara International Airport", "country": "USA"},
    {"code": "ROC", "name": "Rochester", "fullName": "Greater Rochester International Airport", "country": "USA"},
    {"code": "SYR", "name": "Syracuse", "fullName": "Syracuse Hancock International Airport", "country": "USA"},
    {"code": "ALB", "name": "Albany", "fullName": "Albany International Airport", "country": "USA"},

    # ============ NORTH AMERICA - CANADA ============
    {"code": "YYZ", "name": "Toronto", "fullName": "Toronto Pearson International Airport", "country": "Canada"},
    {"code": "YYC", "name": "Calgary", "fullName": "Calgary International Airport", "country": "Canada"},
    {"code": "YVR", "name": "Vancouver", "fullName": "Vancouver International Airport", "country": "Canada"},
    {"code": "YUL", "name": "Montreal", "fullName": "Montréal-Pierre Elliott Trudeau International Airport", "country": "Canada"},
    {"code": "YOW", "name": "Ottawa", "fullName": "Ottawa Macdonald–Cartier International Airport", "country": "Canada"},
    {"code": "YEG", "name": "Edmonton", "fullName": "Edmonton International Airport", "country": "Canada"},
    {"code": "YWG", "name": "Winnipeg", "fullName": "Winnipeg James Armstrong Richardson International Airport", "country": "Canada"},
    {"code": "YHZ", "name": "Halifax", "fullName": "Halifax Stanfield International Airport", "country": "Canada"},
    {"code": "YQB", "name": "Quebec City", "fullName": "Québec City Jean Lesage International Airport", "country": "Canada"},
    {"code": "YXE", "name": "Saskatoon", "fullName": "Saskatoon John G. Diefenbaker International Airport", "country": "Canada"},
    {"code": "YQR", "name": "Regina", "fullName": "Regina International Airport", "country": "Canada"},
    {"code": "YYJ", "name": "Victoria", "fullName": "Victoria International Airport", "country": "Canada"},
    {"code": "YKA", "name": "Kamloops", "fullName": "Kamloops Airport", "country": "Canada"},
    {"code": "YLW", "name": "Kelowna", "fullName": "Kelowna International Airport", "country": "Canada"},
    {"code": "YXY", "name": "Whitehorse", "fullName": "Erik Nielsen Whitehorse International Airport", "country": "Canada"},
    {"code": "YZF", "name": "Yellowknife", "fullName": "Yellowknife Airport", "country": "Canada"},

    # ============ CARIBBEAN & CENTRAL AMERICA ============
    {"code": "CUN", "name": "Cancun", "fullName": "Cancún International Airport", "country": "Mexico"},
    {"code": "MEX", "name": "Mexico City", "fullName": "Mexico City International Airport", "country": "Mexico"},
    {"code": "GDL", "name": "Guadalajara", "fullName": "Guadalajara International Airport", "country": "Mexico"},
    {"code": "MTY", "name": "Monterrey", "fullName": "Monterrey International Airport", "country": "Mexico"},
    {"code": "TIJ", "name": "Tijuana", "fullName": "Tijuana International Airport", "country": "Mexico"},
    {"code": "SJD", "name": "Los Cabos", "fullName": "Los Cabos International Airport", "country": "Mexico"},
    {"code": "PVR", "name": "Puerto Vallarta", "fullName": "Licenciado Gustavo Díaz Ordaz International Airport", "country": "Mexico"},
    {"code": "MID", "name": "Merida", "fullName": "Manuel Crescencio Rejón International Airport", "country": "Mexico"},
    {"code": "HAV", "name": "Havana", "fullName": "José Martí International Airport", "country": "Cuba"},
    {"code": "VRA", "name": "Varadero", "fullName": "Juan Gualberto Gómez Airport", "country": "Cuba"},
    {"code": "SJU", "name": "San Juan", "fullName": "Luis Muñoz Marín International Airport", "country": "Puerto Rico"},
    {"code": "SDQ", "name": "Santo Domingo", "fullName": "Las Américas International Airport", "country": "Dominican Republic"},
    {"code": "PUJ", "name": "Punta Cana", "fullName": "Punta Cana International Airport", "country": "Dominican Republic"},
    {"code": "KIN", "name": "Kingston", "fullName": "Norman Manley International Airport", "country": "Jamaica"},
    {"code": "MBJ", "name": "Montego Bay", "fullName": "Sangster International Airport", "country": "Jamaica"},
    {"code": "NAS", "name": "Nassau", "fullName": "Lynden Pindling International Airport", "country": "Bahamas"},
    {"code": "BGI", "name": "Bridgetown", "fullName": "Grantley Adams International Airport", "country": "Barbados"},
    {"code": "POS", "name": "Port of Spain", "fullName": "Piarco International Airport", "country": "Trinidad"},
    {"code": "AUA", "name": "Aruba", "fullName": "Queen Beatrix International Airport", "country": "Aruba"},
    {"code": "CUR", "name": "Curacao", "fullName": "Curaçao International Airport", "country": "Curacao"},
    {"code": "SXM", "name": "St Maarten", "fullName": "Princess Juliana International Airport", "country": "St Maarten"},
    {"code": "ANU", "name": "Antigua", "fullName": "V.C. Bird International Airport", "country": "Antigua"},
    {"code": "UVF", "name": "St Lucia", "fullName": "Hewanorra International Airport", "country": "St Lucia"},
    {"code": "PTP", "name": "Pointe-a-Pitre", "fullName": "Pointe-à-Pitre Le Raizet Airport", "country": "Guadeloupe"},
    {"code": "FDF", "name": "Fort-de-France", "fullName": "Martinique Aimé Césaire International Airport", "country": "Martinique"},
    {"code": "GND", "name": "Grenada", "fullName": "Maurice Bishop International Airport", "country": "Grenada"},
    {"code": "SVD", "name": "St Vincent", "fullName": "Argyle International Airport", "country": "St Vincent"},
    {"code": "DOM", "name": "Dominica", "fullName": "Douglas–Charles Airport", "country": "Dominica"},
    {"code": "SKB", "name": "St Kitts", "fullName": "Robert L. Bradshaw International Airport", "country": "St Kitts"},
    {"code": "GCM", "name": "Grand Cayman", "fullName": "Owen Roberts International Airport", "country": "Cayman Islands"},
    {"code": "BZE", "name": "Belize City", "fullName": "Philip S.W. Goldson International Airport", "country": "Belize"},
    {"code": "GUA", "name": "Guatemala City", "fullName": "La Aurora International Airport", "country": "Guatemala"},
    {"code": "SAL", "name": "San Salvador", "fullName": "Monseñor Óscar Arnulfo Romero International Airport", "country": "El Salvador"},
    {"code": "TGU", "name": "Tegucigalpa", "fullName": "Toncontín International Airport", "country": "Honduras"},
    {"code": "RTB", "name": "Roatan", "fullName": "Juan Manuel Gálvez International Airport", "country": "Honduras"},
    {"code": "SAP", "name": "San Pedro Sula", "fullName": "Ramón Villeda Morales International Airport", "country": "Honduras"},
    {"code": "MGA", "name": "Managua", "fullName": "Augusto C. Sandino International Airport", "country": "Nicaragua"},
    {"code": "SJO", "name": "San Jose", "fullName": "Juan Santamaría International Airport", "country": "Costa Rica"},
    {"code": "LIR", "name": "Liberia", "fullName": "Daniel Oduber Quirós International Airport", "country": "Costa Rica"},
    {"code": "PTY", "name": "Panama City", "fullName": "Tocumen International Airport", "country": "Panama"},

    # ============ SOUTH AMERICA ============
    {"code": "GRU", "name": "Sao Paulo Guarulhos", "fullName": "São Paulo/Guarulhos International Airport", "country": "Brazil"},
    {"code": "CGH", "name": "Sao Paulo Congonhas", "fullName": "São Paulo/Congonhas Airport", "country": "Brazil"},
    {"code": "GIG", "name": "Rio de Janeiro", "fullName": "Rio de Janeiro–Galeão International Airport", "country": "Brazil"},
    {"code": "SDU", "name": "Rio Santos Dumont", "fullName": "Santos Dumont Airport", "country": "Brazil"},
    {"code": "BSB", "name": "Brasilia", "fullName": "Brasília International Airport", "country": "Brazil"},
    {"code": "CNF", "name": "Belo Horizonte", "fullName": "Belo Horizonte International Airport", "country": "Brazil"},
    {"code": "SSA", "name": "Salvador", "fullName": "Salvador International Airport", "country": "Brazil"},
    {"code": "REC", "name": "Recife", "fullName": "Recife/Guararapes–Gilberto Freyre International Airport", "country": "Brazil"},
    {"code": "FOR", "name": "Fortaleza", "fullName": "Fortaleza International Airport", "country": "Brazil"},
    {"code": "POA", "name": "Porto Alegre", "fullName": "Salgado Filho International Airport", "country": "Brazil"},
    {"code": "CWB", "name": "Curitiba", "fullName": "Afonso Pena International Airport", "country": "Brazil"},
    {"code": "FLN", "name": "Florianopolis", "fullName": "Hercílio Luz International Airport", "country": "Brazil"},
    {"code": "NAT", "name": "Natal", "fullName": "Greater Natal International Airport", "country": "Brazil"},
    {"code": "MAO", "name": "Manaus", "fullName": "Eduardo Gomes International Airport", "country": "Brazil"},
    {"code": "BEL", "name": "Belem", "fullName": "Val de Cans International Airport", "country": "Brazil"},
    {"code": "VCP", "name": "Campinas", "fullName": "Viracopos International Airport", "country": "Brazil"},
    {"code": "EZE", "name": "Buenos Aires Ezeiza", "fullName": "Ministro Pistarini International Airport", "country": "Argentina"},
    {"code": "AEP", "name": "Buenos Aires Aeroparque", "fullName": "Aeroparque Jorge Newbery", "country": "Argentina"},
    {"code": "COR", "name": "Cordoba", "fullName": "Ingeniero Aeronáutico Ambrosio L.V. Taravella International Airport", "country": "Argentina"},
    {"code": "MDZ", "name": "Mendoza", "fullName": "Governor Francisco Gabrielli International Airport", "country": "Argentina"},
    {"code": "BRC", "name": "Bariloche", "fullName": "Teniente Luis Candelaria International Airport", "country": "Argentina"},
    {"code": "USH", "name": "Ushuaia", "fullName": "Malvinas Argentinas International Airport", "country": "Argentina"},
    {"code": "IGR", "name": "Iguazu", "fullName": "Cataratas del Iguazú International Airport", "country": "Argentina"},
    {"code": "SCL", "name": "Santiago", "fullName": "Arturo Merino Benítez International Airport", "country": "Chile"},
    {"code": "PUQ", "name": "Punta Arenas", "fullName": "Presidente Carlos Ibáñez del Campo International Airport", "country": "Chile"},
    {"code": "CCP", "name": "Concepcion", "fullName": "Carriel Sur International Airport", "country": "Chile"},
    {"code": "IQQ", "name": "Iquique", "fullName": "Diego Aracena International Airport", "country": "Chile"},
    {"code": "IPC", "name": "Easter Island", "fullName": "Mataveri International Airport", "country": "Chile"},
    {"code": "LIM", "name": "Lima", "fullName": "Jorge Chávez International Airport", "country": "Peru"},
    {"code": "CUZ", "name": "Cusco", "fullName": "Alejandro Velasco Astete International Airport", "country": "Peru"},
    {"code": "AQP", "name": "Arequipa", "fullName": "Rodríguez Ballón International Airport", "country": "Peru"},
    {"code": "BOG", "name": "Bogota", "fullName": "El Dorado International Airport", "country": "Colombia"},
    {"code": "MDE", "name": "Medellin", "fullName": "José María Córdova International Airport", "country": "Colombia"},
    {"code": "CLO", "name": "Cali", "fullName": "Alfonso Bonilla Aragón International Airport", "country": "Colombia"},
    {"code": "CTG", "name": "Cartagena", "fullName": "Rafael Núñez International Airport", "country": "Colombia"},
    {"code": "BAQ", "name": "Barranquilla", "fullName": "Ernesto Cortissoz International Airport", "country": "Colombia"},
    {"code": "SMR", "name": "Santa Marta", "fullName": "Simón Bolívar International Airport", "country": "Colombia"},
    {"code": "CCS", "name": "Caracas", "fullName": "Simón Bolívar International Airport", "country": "Venezuela"},
    {"code": "UIO", "name": "Quito", "fullName": "Mariscal Sucre International Airport", "country": "Ecuador"},
    {"code": "GYE", "name": "Guayaquil", "fullName": "José Joaquín de Olmedo International Airport", "country": "Ecuador"},
    {"code": "GPS", "name": "Galapagos", "fullName": "Seymour Airport", "country": "Ecuador"},
    {"code": "LPB", "name": "La Paz", "fullName": "El Alto International Airport", "country": "Bolivia"},
    {"code": "VVI", "name": "Santa Cruz", "fullName": "Viru Viru International Airport", "country": "Bolivia"},
    {"code": "ASU", "name": "Asuncion", "fullName": "Silvio Pettirossi International Airport", "country": "Paraguay"},
    {"code": "MVD", "name": "Montevideo", "fullName": "Carrasco International Airport", "country": "Uruguay"},
    {"code": "PUE", "name": "Punta del Este", "fullName": "Capitán de Corbeta Carlos A. Curbelo International Airport", "country": "Uruguay"},
    {"code": "GEO", "name": "Georgetown", "fullName": "Cheddi Jagan International Airport", "country": "Guyana"},
    {"code": "PBM", "name": "Paramaribo", "fullName": "Johan Adolf Pengel International Airport", "country": "Suriname"},
    {"code": "CAY", "name": "Cayenne", "fullName": "Cayenne – Félix Eboué Airport", "country": "French Guiana"},

    # ============ ASIA - EAST ============
    {"code": "PEK", "name": "Beijing Capital", "fullName": "Beijing Capital International Airport", "country": "China"},
    {"code": "PKX", "name": "Beijing Daxing", "fullName": "Beijing Daxing International Airport", "country": "China"},
    {"code": "PVG", "name": "Shanghai Pudong", "fullName": "Shanghai Pudong International Airport", "country": "China"},
    {"code": "SHA", "name": "Shanghai Hongqiao", "fullName": "Shanghai Hongqiao International Airport", "country": "China"},
    {"code": "CAN", "name": "Guangzhou", "fullName": "Guangzhou Baiyun International Airport", "country": "China"},
    {"code": "SZX", "name": "Shenzhen", "fullName": "Shenzhen Bao'an International Airport", "country": "China"},
    {"code": "HKG", "name": "Hong Kong", "fullName": "Hong Kong International Airport", "country": "Hong Kong"},
    {"code": "CTU", "name": "Chengdu", "fullName": "Chengdu Shuangliu International Airport", "country": "China"},
    {"code": "CKG", "name": "Chongqing", "fullName": "Chongqing Jiangbei International Airport", "country": "China"},
    {"code": "KMG", "name": "Kunming", "fullName": "Kunming Changshui International Airport", "country": "China"},
    {"code": "XIY", "name": "Xi'an", "fullName": "Xi'an Xianyang International Airport", "country": "China"},
    {"code": "HGH", "name": "Hangzhou", "fullName": "Hangzhou Xiaoshan International Airport", "country": "China"},
    {"code": "NKG", "name": "Nanjing", "fullName": "Nanjing Lukou International Airport", "country": "China"},
    {"code": "WUH", "name": "Wuhan", "fullName": "Wuhan Tianhe International Airport", "country": "China"},
    {"code": "TAO", "name": "Qingdao", "fullName": "Qingdao Jiaodong International Airport", "country": "China"},
    {"code": "DLC", "name": "Dalian", "fullName": "Dalian Zhoushuizi International Airport", "country": "China"},
    {"code": "SYX", "name": "Sanya", "fullName": "Sanya Phoenix International Airport", "country": "China"},
    {"code": "HAK", "name": "Haikou", "fullName": "Haikou Meilan International Airport", "country": "China"},
    {"code": "XMN", "name": "Xiamen", "fullName": "Xiamen Gaoqi International Airport", "country": "China"},
    {"code": "FOC", "name": "Fuzhou", "fullName": "Fuzhou Changle International Airport", "country": "China"},
    {"code": "CSX", "name": "Changsha", "fullName": "Changsha Huanghua International Airport", "country": "China"},
    {"code": "NNG", "name": "Nanning", "fullName": "Nanning Wuxu International Airport", "country": "China"},
    {"code": "CGO", "name": "Zhengzhou", "fullName": "Zhengzhou Xinzheng International Airport", "country": "China"},
    {"code": "SHE", "name": "Shenyang", "fullName": "Shenyang Taoxian International Airport", "country": "China"},
    {"code": "TSN", "name": "Tianjin", "fullName": "Tianjin Binhai International Airport", "country": "China"},
    {"code": "URC", "name": "Urumqi", "fullName": "Ürümqi Diwopu International Airport", "country": "China"},
    {"code": "HRB", "name": "Harbin", "fullName": "Harbin Taiping International Airport", "country": "China"},
    {"code": "TNA", "name": "Jinan", "fullName": "Jinan Yaoqiang International Airport", "country": "China"},
    {"code": "NRT", "name": "Tokyo Narita", "fullName": "Narita International Airport", "country": "Japan"},
    {"code": "HND", "name": "Tokyo Haneda", "fullName": "Haneda Airport", "country": "Japan"},
    {"code": "KIX", "name": "Osaka Kansai", "fullName": "Kansai International Airport", "country": "Japan"},
    {"code": "ITM", "name": "Osaka Itami", "fullName": "Osaka International Airport", "country": "Japan"},
    {"code": "NGO", "name": "Nagoya", "fullName": "Chubu Centrair International Airport", "country": "Japan"},
    {"code": "FUK", "name": "Fukuoka", "fullName": "Fukuoka Airport", "country": "Japan"},
    {"code": "CTS", "name": "Sapporo", "fullName": "New Chitose Airport", "country": "Japan"},
    {"code": "OKA", "name": "Okinawa", "fullName": "Naha Airport", "country": "Japan"},
    {"code": "KOJ", "name": "Kagoshima", "fullName": "Kagoshima Airport", "country": "Japan"},
    {"code": "HIJ", "name": "Hiroshima", "fullName": "Hiroshima Airport", "country": "Japan"},
    {"code": "SDJ", "name": "Sendai", "fullName": "Sendai Airport", "country": "Japan"},
    {"code": "KMQ", "name": "Komatsu", "fullName": "Komatsu Airport", "country": "Japan"},
    {"code": "ICN", "name": "Seoul Incheon", "fullName": "Incheon International Airport", "country": "South Korea"},
    {"code": "GMP", "name": "Seoul Gimpo", "fullName": "Gimpo International Airport", "country": "South Korea"},
    {"code": "PUS", "name": "Busan", "fullName": "Gimhae International Airport", "country": "South Korea"},
    {"code": "CJU", "name": "Jeju", "fullName": "Jeju International Airport", "country": "South Korea"},
    {"code": "TAE", "name": "Daegu", "fullName": "Daegu International Airport", "country": "South Korea"},
    {"code": "TPE", "name": "Taipei Taoyuan", "fullName": "Taiwan Taoyuan International Airport", "country": "Taiwan"},
    {"code": "TSA", "name": "Taipei Songshan", "fullName": "Taipei Songshan Airport", "country": "Taiwan"},
    {"code": "KHH", "name": "Kaohsiung", "fullName": "Kaohsiung International Airport", "country": "Taiwan"},
    {"code": "MFM", "name": "Macau", "fullName": "Macau International Airport", "country": "Macau"},
    {"code": "ULN", "name": "Ulaanbaatar", "fullName": "Chinggis Khaan International Airport", "country": "Mongolia"},
    {"code": "FNJ", "name": "Pyongyang", "fullName": "Pyongyang International Airport", "country": "North Korea"},

    # ============ ASIA - SOUTHEAST ============
    {"code": "SIN", "name": "Singapore", "fullName": "Singapore Changi Airport", "country": "Singapore"},
    {"code": "BKK", "name": "Bangkok Suvarnabhumi", "fullName": "Suvarnabhumi Airport", "country": "Thailand"},
    {"code": "DMK", "name": "Bangkok Don Mueang", "fullName": "Don Mueang International Airport", "country": "Thailand"},
    {"code": "HKT", "name": "Phuket", "fullName": "Phuket International Airport", "country": "Thailand"},
    {"code": "CNX", "name": "Chiang Mai", "fullName": "Chiang Mai International Airport", "country": "Thailand"},
    {"code": "USM", "name": "Koh Samui", "fullName": "Samui Airport", "country": "Thailand"},
    {"code": "KBV", "name": "Krabi", "fullName": "Krabi Airport", "country": "Thailand"},
    {"code": "CEI", "name": "Chiang Rai", "fullName": "Mae Fah Luang – Chiang Rai International Airport", "country": "Thailand"},
    {"code": "HDY", "name": "Hat Yai", "fullName": "Hat Yai International Airport", "country": "Thailand"},
    {"code": "KUL", "name": "Kuala Lumpur", "fullName": "Kuala Lumpur International Airport", "country": "Malaysia"},
    {"code": "SZB", "name": "Kuala Lumpur Subang", "fullName": "Sultan Abdul Aziz Shah Airport", "country": "Malaysia"},
    {"code": "PEN", "name": "Penang", "fullName": "Penang International Airport", "country": "Malaysia"},
    {"code": "LGK", "name": "Langkawi", "fullName": "Langkawi International Airport", "country": "Malaysia"},
    {"code": "BKI", "name": "Kota Kinabalu", "fullName": "Kota Kinabalu International Airport", "country": "Malaysia"},
    {"code": "KCH", "name": "Kuching", "fullName": "Kuching International Airport", "country": "Malaysia"},
    {"code": "JHB", "name": "Johor Bahru", "fullName": "Senai International Airport", "country": "Malaysia"},
    {"code": "MYY", "name": "Miri", "fullName": "Miri Airport", "country": "Malaysia"},
    {"code": "BWN", "name": "Bandar Seri Begawan", "fullName": "Brunei International Airport", "country": "Brunei"},
    {"code": "CGK", "name": "Jakarta", "fullName": "Soekarno–Hatta International Airport", "country": "Indonesia"},
    {"code": "HLP", "name": "Jakarta Halim", "fullName": "Halim Perdanakusuma Airport", "country": "Indonesia"},
    {"code": "DPS", "name": "Bali Denpasar", "fullName": "Ngurah Rai International Airport", "country": "Indonesia"},
    {"code": "SUB", "name": "Surabaya", "fullName": "Juanda International Airport", "country": "Indonesia"},
    {"code": "UPG", "name": "Makassar", "fullName": "Sultan Hasanuddin International Airport", "country": "Indonesia"},
    {"code": "JOG", "name": "Yogyakarta", "fullName": "Adisucipto International Airport", "country": "Indonesia"},
    {"code": "KNO", "name": "Medan", "fullName": "Kualanamu International Airport", "country": "Indonesia"},
    {"code": "BDO", "name": "Bandung", "fullName": "Husein Sastranegara International Airport", "country": "Indonesia"},
    {"code": "PLM", "name": "Palembang", "fullName": "Sultan Mahmud Badaruddin II International Airport", "country": "Indonesia"},
    {"code": "SOC", "name": "Solo", "fullName": "Adisumarmo International Airport", "country": "Indonesia"},
    {"code": "LOP", "name": "Lombok", "fullName": "Lombok International Airport", "country": "Indonesia"},
    {"code": "MNL", "name": "Manila", "fullName": "Ninoy Aquino International Airport", "country": "Philippines"},
    {"code": "CEB", "name": "Cebu", "fullName": "Mactan–Cebu International Airport", "country": "Philippines"},
    {"code": "DVO", "name": "Davao", "fullName": "Francisco Bangoy International Airport", "country": "Philippines"},
    {"code": "CRK", "name": "Clark", "fullName": "Clark International Airport", "country": "Philippines"},
    {"code": "ILO", "name": "Iloilo", "fullName": "Iloilo International Airport", "country": "Philippines"},
    {"code": "BCD", "name": "Bacolod", "fullName": "Bacolod–Silay Airport", "country": "Philippines"},
    {"code": "SGN", "name": "Ho Chi Minh City", "fullName": "Tan Son Nhat International Airport", "country": "Vietnam"},
    {"code": "HAN", "name": "Hanoi", "fullName": "Noi Bai International Airport", "country": "Vietnam"},
    {"code": "DAD", "name": "Da Nang", "fullName": "Da Nang International Airport", "country": "Vietnam"},
    {"code": "CXR", "name": "Nha Trang", "fullName": "Cam Ranh International Airport", "country": "Vietnam"},
    {"code": "PQC", "name": "Phu Quoc", "fullName": "Phu Quoc International Airport", "country": "Vietnam"},
    {"code": "VDO", "name": "Van Don", "fullName": "Van Don International Airport", "country": "Vietnam"},
    {"code": "PNH", "name": "Phnom Penh", "fullName": "Phnom Penh International Airport", "country": "Cambodia"},
    {"code": "REP", "name": "Siem Reap", "fullName": "Siem Reap International Airport", "country": "Cambodia"},
    {"code": "VTE", "name": "Vientiane", "fullName": "Wattay International Airport", "country": "Laos"},
    {"code": "LPQ", "name": "Luang Prabang", "fullName": "Luang Prabang International Airport", "country": "Laos"},
    {"code": "RGN", "name": "Yangon", "fullName": "Yangon International Airport", "country": "Myanmar"},
    {"code": "MDL", "name": "Mandalay", "fullName": "Mandalay International Airport", "country": "Myanmar"},
    {"code": "NYT", "name": "Naypyidaw", "fullName": "Naypyidaw International Airport", "country": "Myanmar"},
    {"code": "DIL", "name": "Dili", "fullName": "Presidente Nicolau Lobato International Airport", "country": "Timor-Leste"},

    # ============ ASIA - SOUTH ============
    {"code": "DEL", "name": "New Delhi", "fullName": "Indira Gandhi International Airport", "country": "India"},
    {"code": "BOM", "name": "Mumbai", "fullName": "Chhatrapati Shivaji Maharaj International Airport", "country": "India"},
    {"code": "BLR", "name": "Bangalore", "fullName": "Kempegowda International Airport", "country": "India"},
    {"code": "MAA", "name": "Chennai", "fullName": "Chennai International Airport", "country": "India"},
    {"code": "CCU", "name": "Kolkata", "fullName": "Netaji Subhas Chandra Bose International Airport", "country": "India"},
    {"code": "HYD", "name": "Hyderabad", "fullName": "Rajiv Gandhi International Airport", "country": "India"},
    {"code": "COK", "name": "Kochi", "fullName": "Cochin International Airport", "country": "India"},
    {"code": "AMD", "name": "Ahmedabad", "fullName": "Sardar Vallabhbhai Patel International Airport", "country": "India"},
    {"code": "GOI", "name": "Goa", "fullName": "Goa International Airport", "country": "India"},
    {"code": "JAI", "name": "Jaipur", "fullName": "Jaipur International Airport", "country": "India"},
    {"code": "PNQ", "name": "Pune", "fullName": "Pune Airport", "country": "India"},
    {"code": "LKO", "name": "Lucknow", "fullName": "Chaudhary Charan Singh International Airport", "country": "India"},
    {"code": "GAU", "name": "Guwahati", "fullName": "Lokpriya Gopinath Bordoloi International Airport", "country": "India"},
    {"code": "TRV", "name": "Thiruvananthapuram", "fullName": "Trivandrum International Airport", "country": "India"},
    {"code": "SXR", "name": "Srinagar", "fullName": "Sheikh ul-Alam International Airport", "country": "India"},
    {"code": "VNS", "name": "Varanasi", "fullName": "Lal Bahadur Shastri International Airport", "country": "India"},
    {"code": "IXC", "name": "Chandigarh", "fullName": "Chandigarh International Airport", "country": "India"},
    {"code": "IXB", "name": "Bagdogra", "fullName": "Bagdogra Airport", "country": "India"},
    {"code": "IXE", "name": "Mangalore", "fullName": "Mangalore International Airport", "country": "India"},
    {"code": "NAG", "name": "Nagpur", "fullName": "Dr. Babasaheb Ambedkar International Airport", "country": "India"},
    {"code": "PAT", "name": "Patna", "fullName": "Jay Prakash Narayan International Airport", "country": "India"},
    {"code": "CJB", "name": "Coimbatore", "fullName": "Coimbatore International Airport", "country": "India"},
    {"code": "BBI", "name": "Bhubaneswar", "fullName": "Biju Patnaik International Airport", "country": "India"},
    {"code": "IXZ", "name": "Port Blair", "fullName": "Veer Savarkar International Airport", "country": "India"},
    {"code": "CMB", "name": "Colombo", "fullName": "Bandaranaike International Airport", "country": "Sri Lanka"},
    {"code": "HRI", "name": "Mattala", "fullName": "Mattala Rajapaksa International Airport", "country": "Sri Lanka"},
    {"code": "DAC", "name": "Dhaka", "fullName": "Hazrat Shahjalal International Airport", "country": "Bangladesh"},
    {"code": "CGP", "name": "Chittagong", "fullName": "Shah Amanat International Airport", "country": "Bangladesh"},
    {"code": "KTM", "name": "Kathmandu", "fullName": "Tribhuvan International Airport", "country": "Nepal"},
    {"code": "PKR", "name": "Pokhara", "fullName": "Pokhara International Airport", "country": "Nepal"},
    {"code": "ISB", "name": "Islamabad", "fullName": "Islamabad International Airport", "country": "Pakistan"},
    {"code": "KHI", "name": "Karachi", "fullName": "Jinnah International Airport", "country": "Pakistan"},
    {"code": "LHE", "name": "Lahore", "fullName": "Allama Iqbal International Airport", "country": "Pakistan"},
    {"code": "PEW", "name": "Peshawar", "fullName": "Bacha Khan International Airport", "country": "Pakistan"},
    {"code": "MUX", "name": "Multan", "fullName": "Multan International Airport", "country": "Pakistan"},
    {"code": "SKT", "name": "Sialkot", "fullName": "Sialkot International Airport", "country": "Pakistan"},
    {"code": "KBL", "name": "Kabul", "fullName": "Hamid Karzai International Airport", "country": "Afghanistan"},
    {"code": "PBH", "name": "Paro", "fullName": "Paro International Airport", "country": "Bhutan"},

    # ============ OCEANIA ============
    {"code": "SYD", "name": "Sydney", "fullName": "Sydney Kingsford Smith Airport", "country": "Australia"},
    {"code": "MEL", "name": "Melbourne", "fullName": "Melbourne Airport", "country": "Australia"},
    {"code": "BNE", "name": "Brisbane", "fullName": "Brisbane Airport", "country": "Australia"},
    {"code": "PER", "name": "Perth", "fullName": "Perth Airport", "country": "Australia"},
    {"code": "ADL", "name": "Adelaide", "fullName": "Adelaide Airport", "country": "Australia"},
    {"code": "CBR", "name": "Canberra", "fullName": "Canberra Airport", "country": "Australia"},
    {"code": "OOL", "name": "Gold Coast", "fullName": "Gold Coast Airport", "country": "Australia"},
    {"code": "CNS", "name": "Cairns", "fullName": "Cairns Airport", "country": "Australia"},
    {"code": "DRW", "name": "Darwin", "fullName": "Darwin International Airport", "country": "Australia"},
    {"code": "HBA", "name": "Hobart", "fullName": "Hobart International Airport", "country": "Australia"},
    {"code": "TSV", "name": "Townsville", "fullName": "Townsville Airport", "country": "Australia"},
    {"code": "NTL", "name": "Newcastle", "fullName": "Newcastle Airport", "country": "Australia"},
    {"code": "LST", "name": "Launceston", "fullName": "Launceston Airport", "country": "Australia"},
    {"code": "MCY", "name": "Sunshine Coast", "fullName": "Sunshine Coast Airport", "country": "Australia"},
    {"code": "AKL", "name": "Auckland", "fullName": "Auckland Airport", "country": "New Zealand"},
    {"code": "WLG", "name": "Wellington", "fullName": "Wellington International Airport", "country": "New Zealand"},
    {"code": "CHC", "name": "Christchurch", "fullName": "Christchurch International Airport", "country": "New Zealand"},
    {"code": "ZQN", "name": "Queenstown", "fullName": "Queenstown Airport", "country": "New Zealand"},
    {"code": "DUD", "name": "Dunedin", "fullName": "Dunedin Airport", "country": "New Zealand"},
    {"code": "ROT", "name": "Rotorua", "fullName": "Rotorua Airport", "country": "New Zealand"},
    {"code": "NPE", "name": "Napier", "fullName": "Hawke's Bay Airport", "country": "New Zealand"},
    {"code": "PMR", "name": "Palmerston North", "fullName": "Palmerston North Airport", "country": "New Zealand"},
    {"code": "NSN", "name": "Nelson", "fullName": "Nelson Airport", "country": "New Zealand"},
    {"code": "NAN", "name": "Nadi", "fullName": "Nadi International Airport", "country": "Fiji"},
    {"code": "SUV", "name": "Suva", "fullName": "Nausori International Airport", "country": "Fiji"},
    {"code": "PPT", "name": "Tahiti", "fullName": "Faa'a International Airport", "country": "French Polynesia"},
    {"code": "BOB", "name": "Bora Bora", "fullName": "Bora Bora Airport", "country": "French Polynesia"},
    {"code": "NOU", "name": "Noumea", "fullName": "La Tontouta International Airport", "country": "New Caledonia"},
    {"code": "APW", "name": "Apia", "fullName": "Faleolo International Airport", "country": "Samoa"},
    {"code": "VLI", "name": "Port Vila", "fullName": "Bauerfield International Airport", "country": "Vanuatu"},
    {"code": "TBU", "name": "Nuku'alofa", "fullName": "Fua'amotu International Airport", "country": "Tonga"},
    {"code": "ROR", "name": "Koror", "fullName": "Roman Tmetuchl International Airport", "country": "Palau"},
    {"code": "GUM", "name": "Guam", "fullName": "Antonio B. Won Pat International Airport", "country": "Guam"},
    {"code": "SPN", "name": "Saipan", "fullName": "Francisco C. Ada/Saipan International Airport", "country": "Northern Mariana Islands"},
    {"code": "POM", "name": "Port Moresby", "fullName": "Jacksons International Airport", "country": "Papua New Guinea"},
    {"code": "HIR", "name": "Honiara", "fullName": "Honiara International Airport", "country": "Solomon Islands"},
    {"code": "TRW", "name": "Tarawa", "fullName": "Bonriki International Airport", "country": "Kiribati"},
    {"code": "FUN", "name": "Funafuti", "fullName": "Funafuti International Airport", "country": "Tuvalu"},
    {"code": "INU", "name": "Nauru", "fullName": "Nauru International Airport", "country": "Nauru"},
    {"code": "MAJ", "name": "Majuro", "fullName": "Marshall Islands International Airport", "country": "Marshall Islands"},
    {"code": "TKK", "name": "Chuuk", "fullName": "Chuuk International Airport", "country": "Micronesia"},
    {"code": "PNI", "name": "Pohnpei", "fullName": "Pohnpei International Airport", "country": "Micronesia"},
]

# Cities for experiences/attractions
CITIES = [
    # Nigeria
    {"lat": 6.5244, "lng": 3.3792, "name": "Lagos", "country": "Nigeria"},
    {"lat": 9.0765, "lng": 7.3986, "name": "Abuja", "country": "Nigeria"},
    {"lat": 4.8156, "lng": 7.0498, "name": "Port Harcourt", "country": "Nigeria"},
    {"lat": 12.0022, "lng": 8.5920, "name": "Kano", "country": "Nigeria"},
    {"lat": 7.3775, "lng": 3.9470, "name": "Ibadan", "country": "Nigeria"},
    
    # Africa
    {"lat": 5.6037, "lng": -0.187, "name": "Accra", "country": "Ghana"},
    {"lat": -1.2921, "lng": 36.8219, "name": "Nairobi", "country": "Kenya"},
    {"lat": -26.2041, "lng": 28.0473, "name": "Johannesburg", "country": "South Africa"},
    {"lat": -33.9249, "lng": 18.4241, "name": "Cape Town", "country": "South Africa"},
    {"lat": 30.0444, "lng": 31.2357, "name": "Cairo", "country": "Egypt"},
    {"lat": 31.6295, "lng": -7.9811, "name": "Marrakech", "country": "Morocco"},
    {"lat": 33.5731, "lng": -7.5898, "name": "Casablanca", "country": "Morocco"},
    {"lat": -6.1630, "lng": 39.2026, "name": "Zanzibar", "country": "Tanzania"},
    {"lat": -17.8252, "lng": 25.8576, "name": "Victoria Falls", "country": "Zimbabwe"},
    
    # Middle East
    {"lat": 25.2048, "lng": 55.2708, "name": "Dubai", "country": "UAE"},
    {"lat": 24.4539, "lng": 54.3773, "name": "Abu Dhabi", "country": "UAE"},
    {"lat": 25.2854, "lng": 51.5310, "name": "Doha", "country": "Qatar"},
    {"lat": 21.4858, "lng": 39.1925, "name": "Jeddah", "country": "Saudi Arabia"},
    {"lat": 21.3891, "lng": 39.8579, "name": "Mecca", "country": "Saudi Arabia"},
    {"lat": 31.7683, "lng": 35.2137, "name": "Jerusalem", "country": "Israel"},
    {"lat": 32.0853, "lng": 34.7818, "name": "Tel Aviv", "country": "Israel"},
    {"lat": 41.0082, "lng": 28.9784, "name": "Istanbul", "country": "Turkey"},
    {"lat": 36.8969, "lng": 30.7133, "name": "Antalya", "country": "Turkey"},
    {"lat": 33.8869, "lng": 35.5131, "name": "Beirut", "country": "Lebanon"},
    {"lat": 30.0444, "lng": 35.4444, "name": "Petra", "country": "Jordan"},
    
    # Europe
    {"lat": 51.5074, "lng": -0.1278, "name": "London", "country": "UK"},
    {"lat": 48.8566, "lng": 2.3522, "name": "Paris", "country": "France"},
    {"lat": 52.5200, "lng": 13.4050, "name": "Berlin", "country": "Germany"},
    {"lat": 48.1351, "lng": 11.5820, "name": "Munich", "country": "Germany"},
    {"lat": 52.3676, "lng": 4.9041, "name": "Amsterdam", "country": "Netherlands"},
    {"lat": 41.9028, "lng": 12.4964, "name": "Rome", "country": "Italy"},
    {"lat": 45.4642, "lng": 9.1900, "name": "Milan", "country": "Italy"},
    {"lat": 45.4408, "lng": 12.3155, "name": "Venice", "country": "Italy"},
    {"lat": 43.7696, "lng": 11.2558, "name": "Florence", "country": "Italy"},
    {"lat": 41.3851, "lng": 2.1734, "name": "Barcelona", "country": "Spain"},
    {"lat": 40.4168, "lng": -3.7038, "name": "Madrid", "country": "Spain"},
    {"lat": 38.7223, "lng": -9.1393, "name": "Lisbon", "country": "Portugal"},
    {"lat": 41.1579, "lng": -8.6291, "name": "Porto", "country": "Portugal"},
    {"lat": 47.4979, "lng": 19.0402, "name": "Budapest", "country": "Hungary"},
    {"lat": 50.0755, "lng": 14.4378, "name": "Prague", "country": "Czech Republic"},
    {"lat": 48.2082, "lng": 16.3738, "name": "Vienna", "country": "Austria"},
    {"lat": 37.9838, "lng": 23.7275, "name": "Athens", "country": "Greece"},
    {"lat": 36.4018, "lng": 25.4596, "name": "Santorini", "country": "Greece"},
    {"lat": 43.7384, "lng": 7.4246, "name": "Monaco", "country": "Monaco"},
    {"lat": 43.2965, "lng": 5.3698, "name": "Marseille", "country": "France"},
    {"lat": 43.7102, "lng": 7.2620, "name": "Nice", "country": "France"},
    {"lat": 55.7558, "lng": 37.6173, "name": "Moscow", "country": "Russia"},
    {"lat": 59.9311, "lng": 30.3609, "name": "St Petersburg", "country": "Russia"},
    {"lat": 59.3293, "lng": 18.0686, "name": "Stockholm", "country": "Sweden"},
    {"lat": 55.6761, "lng": 12.5683, "name": "Copenhagen", "country": "Denmark"},
    {"lat": 59.9139, "lng": 10.7522, "name": "Oslo", "country": "Norway"},
    {"lat": 60.1699, "lng": 24.9384, "name": "Helsinki", "country": "Finland"},
    {"lat": 64.1466, "lng": -21.9426, "name": "Reykjavik", "country": "Iceland"},
    {"lat": 53.3498, "lng": -6.2603, "name": "Dublin", "country": "Ireland"},
    {"lat": 55.9533, "lng": -3.1883, "name": "Edinburgh", "country": "UK"},
    {"lat": 53.4808, "lng": -2.2426, "name": "Manchester", "country": "UK"},
    {"lat": 47.3769, "lng": 8.5417, "name": "Zurich", "country": "Switzerland"},
    {"lat": 46.2044, "lng": 6.1432, "name": "Geneva", "country": "Switzerland"},
    {"lat": 50.8503, "lng": 4.3517, "name": "Brussels", "country": "Belgium"},
    {"lat": 50.1109, "lng": 8.6821, "name": "Frankfurt", "country": "Germany"},
    {"lat": 42.6977, "lng": 23.3219, "name": "Sofia", "country": "Bulgaria"},
    {"lat": 44.4268, "lng": 26.1025, "name": "Bucharest", "country": "Romania"},
    {"lat": 52.2297, "lng": 21.0122, "name": "Warsaw", "country": "Poland"},
    {"lat": 50.0647, "lng": 19.9450, "name": "Krakow", "country": "Poland"},
    {"lat": 45.8150, "lng": 15.9819, "name": "Zagreb", "country": "Croatia"},
    {"lat": 42.6507, "lng": 18.0944, "name": "Dubrovnik", "country": "Croatia"},
    {"lat": 43.5081, "lng": 16.4402, "name": "Split", "country": "Croatia"},
    
    # Americas
    {"lat": 40.7128, "lng": -74.006, "name": "New York", "country": "USA"},
    {"lat": 34.0522, "lng": -118.2437, "name": "Los Angeles", "country": "USA"},
    {"lat": 41.8781, "lng": -87.6298, "name": "Chicago", "country": "USA"},
    {"lat": 25.7617, "lng": -80.1918, "name": "Miami", "country": "USA"},
    {"lat": 36.1699, "lng": -115.1398, "name": "Las Vegas", "country": "USA"},
    {"lat": 37.7749, "lng": -122.4194, "name": "San Francisco", "country": "USA"},
    {"lat": 47.6062, "lng": -122.3321, "name": "Seattle", "country": "USA"},
    {"lat": 28.5383, "lng": -81.3792, "name": "Orlando", "country": "USA"},
    {"lat": 36.1627, "lng": -86.7816, "name": "Nashville", "country": "USA"},
    {"lat": 29.7604, "lng": -95.3698, "name": "Houston", "country": "USA"},
    {"lat": 30.2672, "lng": -97.7431, "name": "Austin", "country": "USA"},
    {"lat": 32.7767, "lng": -96.7970, "name": "Dallas", "country": "USA"},
    {"lat": 33.4484, "lng": -112.0740, "name": "Phoenix", "country": "USA"},
    {"lat": 39.7392, "lng": -104.9903, "name": "Denver", "country": "USA"},
    {"lat": 38.9072, "lng": -77.0369, "name": "Washington DC", "country": "USA"},
    {"lat": 42.3601, "lng": -71.0589, "name": "Boston", "country": "USA"},
    {"lat": 21.3069, "lng": -157.8583, "name": "Honolulu", "country": "USA"},
    {"lat": 43.6532, "lng": -79.3832, "name": "Toronto", "country": "Canada"},
    {"lat": 49.2827, "lng": -123.1207, "name": "Vancouver", "country": "Canada"},
    {"lat": 45.5017, "lng": -73.5673, "name": "Montreal", "country": "Canada"},
    {"lat": 19.4326, "lng": -99.1332, "name": "Mexico City", "country": "Mexico"},
    {"lat": 21.1619, "lng": -86.8515, "name": "Cancun", "country": "Mexico"},
    {"lat": 20.6534, "lng": -105.2253, "name": "Puerto Vallarta", "country": "Mexico"},
    {"lat": -22.9068, "lng": -43.1729, "name": "Rio de Janeiro", "country": "Brazil"},
    {"lat": -23.5505, "lng": -46.6333, "name": "Sao Paulo", "country": "Brazil"},
    {"lat": -34.6037, "lng": -58.3816, "name": "Buenos Aires", "country": "Argentina"},
    {"lat": -33.4489, "lng": -70.6693, "name": "Santiago", "country": "Chile"},
    {"lat": -12.0464, "lng": -77.0428, "name": "Lima", "country": "Peru"},
    {"lat": -13.5319, "lng": -71.9675, "name": "Cusco", "country": "Peru"},
    {"lat": 4.7110, "lng": -74.0721, "name": "Bogota", "country": "Colombia"},
    {"lat": 6.2476, "lng": -75.5658, "name": "Medellin", "country": "Colombia"},
    {"lat": 10.3910, "lng": -75.4794, "name": "Cartagena", "country": "Colombia"},
    {"lat": 18.4655, "lng": -66.1057, "name": "San Juan", "country": "Puerto Rico"},
    {"lat": 23.1136, "lng": -82.3666, "name": "Havana", "country": "Cuba"},
    {"lat": 18.4861, "lng": -69.9312, "name": "Santo Domingo", "country": "Dominican Republic"},
    {"lat": 18.5204, "lng": -68.4055, "name": "Punta Cana", "country": "Dominican Republic"},
    {"lat": 18.4655, "lng": -77.9286, "name": "Montego Bay", "country": "Jamaica"},
    {"lat": 25.0343, "lng": -77.3963, "name": "Nassau", "country": "Bahamas"},
    {"lat": 12.4964, "lng": -69.9692, "name": "Aruba", "country": "Aruba"},
    
    # Asia
    {"lat": 1.3521, "lng": 103.8198, "name": "Singapore", "country": "Singapore"},
    {"lat": 13.7563, "lng": 100.5018, "name": "Bangkok", "country": "Thailand"},
    {"lat": 7.8804, "lng": 98.3923, "name": "Phuket", "country": "Thailand"},
    {"lat": 18.7883, "lng": 98.9853, "name": "Chiang Mai", "country": "Thailand"},
    {"lat": 3.1390, "lng": 101.6869, "name": "Kuala Lumpur", "country": "Malaysia"},
    {"lat": 6.2088, "lng": 116.2283, "name": "Kota Kinabalu", "country": "Malaysia"},
    {"lat": -6.2088, "lng": 106.8456, "name": "Jakarta", "country": "Indonesia"},
    {"lat": -8.3405, "lng": 115.0920, "name": "Bali", "country": "Indonesia"},
    {"lat": -7.9706, "lng": 112.6304, "name": "Yogyakarta", "country": "Indonesia"},
    {"lat": 14.5995, "lng": 120.9842, "name": "Manila", "country": "Philippines"},
    {"lat": 10.3157, "lng": 123.8854, "name": "Cebu", "country": "Philippines"},
    {"lat": 9.9312, "lng": 126.0096, "name": "Siargao", "country": "Philippines"},
    {"lat": 10.7769, "lng": 106.7009, "name": "Ho Chi Minh City", "country": "Vietnam"},
    {"lat": 21.0285, "lng": 105.8542, "name": "Hanoi", "country": "Vietnam"},
    {"lat": 16.0544, "lng": 108.2022, "name": "Da Nang", "country": "Vietnam"},
    {"lat": 20.8449, "lng": 106.6881, "name": "Ha Long Bay", "country": "Vietnam"},
    {"lat": 15.8700, "lng": 100.9925, "name": "Hoi An", "country": "Vietnam"},
    {"lat": 11.5564, "lng": 104.9282, "name": "Phnom Penh", "country": "Cambodia"},
    {"lat": 13.3671, "lng": 103.8448, "name": "Siem Reap", "country": "Cambodia"},
    {"lat": 22.3193, "lng": 114.1694, "name": "Hong Kong", "country": "Hong Kong"},
    {"lat": 22.1987, "lng": 113.5439, "name": "Macau", "country": "Macau"},
    {"lat": 25.0330, "lng": 121.5654, "name": "Taipei", "country": "Taiwan"},
    {"lat": 35.6762, "lng": 139.6503, "name": "Tokyo", "country": "Japan"},
    {"lat": 34.6937, "lng": 135.5023, "name": "Osaka", "country": "Japan"},
    {"lat": 35.0116, "lng": 135.7681, "name": "Kyoto", "country": "Japan"},
    {"lat": 43.0618, "lng": 141.3545, "name": "Sapporo", "country": "Japan"},
    {"lat": 26.2124, "lng": 127.6809, "name": "Okinawa", "country": "Japan"},
    {"lat": 37.5665, "lng": 126.9780, "name": "Seoul", "country": "South Korea"},
    {"lat": 35.1796, "lng": 129.0756, "name": "Busan", "country": "South Korea"},
    {"lat": 33.4996, "lng": 126.5312, "name": "Jeju", "country": "South Korea"},
    {"lat": 39.9042, "lng": 116.4074, "name": "Beijing", "country": "China"},
    {"lat": 31.2304, "lng": 121.4737, "name": "Shanghai", "country": "China"},
    {"lat": 23.1291, "lng": 113.2644, "name": "Guangzhou", "country": "China"},
    {"lat": 22.3964, "lng": 114.1095, "name": "Shenzhen", "country": "China"},
    {"lat": 34.2658, "lng": 108.9541, "name": "Xi'an", "country": "China"},
    {"lat": 30.5728, "lng": 104.0668, "name": "Chengdu", "country": "China"},
    {"lat": 25.2744, "lng": 110.2903, "name": "Guilin", "country": "China"},
    {"lat": 28.6139, "lng": 77.2090, "name": "New Delhi", "country": "India"},
    {"lat": 19.0760, "lng": 72.8777, "name": "Mumbai", "country": "India"},
    {"lat": 12.9716, "lng": 77.5946, "name": "Bangalore", "country": "India"},
    {"lat": 27.1767, "lng": 78.0081, "name": "Agra", "country": "India"},
    {"lat": 26.9124, "lng": 75.7873, "name": "Jaipur", "country": "India"},
    {"lat": 15.4909, "lng": 73.8278, "name": "Goa", "country": "India"},
    {"lat": 9.9312, "lng": 76.2673, "name": "Kochi", "country": "India"},
    {"lat": 25.3176, "lng": 82.9739, "name": "Varanasi", "country": "India"},
    {"lat": 22.5726, "lng": 88.3639, "name": "Kolkata", "country": "India"},
    {"lat": 6.9271, "lng": 79.8612, "name": "Colombo", "country": "Sri Lanka"},
    {"lat": 7.2936, "lng": 80.6350, "name": "Kandy", "country": "Sri Lanka"},
    {"lat": 6.0329, "lng": 80.2168, "name": "Galle", "country": "Sri Lanka"},
    {"lat": 27.7172, "lng": 85.3240, "name": "Kathmandu", "country": "Nepal"},
    {"lat": 28.2096, "lng": 83.9856, "name": "Pokhara", "country": "Nepal"},
    {"lat": 4.1755, "lng": 73.5093, "name": "Male", "country": "Maldives"},
    
    # Oceania
    {"lat": -33.8688, "lng": 151.2093, "name": "Sydney", "country": "Australia"},
    {"lat": -37.8136, "lng": 144.9631, "name": "Melbourne", "country": "Australia"},
    {"lat": -27.4698, "lng": 153.0251, "name": "Brisbane", "country": "Australia"},
    {"lat": -31.9505, "lng": 115.8605, "name": "Perth", "country": "Australia"},
    {"lat": -28.0167, "lng": 153.4000, "name": "Gold Coast", "country": "Australia"},
    {"lat": -16.9186, "lng": 145.7781, "name": "Cairns", "country": "Australia"},
    {"lat": -36.8485, "lng": 174.7633, "name": "Auckland", "country": "New Zealand"},
    {"lat": -41.2866, "lng": 174.7756, "name": "Wellington", "country": "New Zealand"},
    {"lat": -43.5321, "lng": 172.6362, "name": "Christchurch", "country": "New Zealand"},
    {"lat": -45.0312, "lng": 168.6626, "name": "Queenstown", "country": "New Zealand"},
    {"lat": -17.7765, "lng": 177.4356, "name": "Fiji", "country": "Fiji"},
    {"lat": -17.5334, "lng": -149.5667, "name": "Tahiti", "country": "French Polynesia"},
    {"lat": -16.5004, "lng": -151.7415, "name": "Bora Bora", "country": "French Polynesia"},
]
